CREATE TABLE IF NOT EXISTS tv_shows (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  original_title TEXT        NOT NULL,
  year           INT,
  description    TEXT,
  slug           TEXT,
  fingerprint    TEXT        NOT NULL UNIQUE,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_tv_shows_year ON tv_shows(year);

CREATE TABLE IF NOT EXISTS tv_show_titles (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  show_id     BIGINT      NOT NULL REFERENCES tv_shows(id) ON DELETE CASCADE,
  title      TEXT        NOT NULL,
  locale     TEXT,
  source     TEXT        NOT NULL CHECK (source IN ('PLEX', 'MANUAL')),
  is_primary BOOLEAN     NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_tv_show_titles_show_title_source
ON tv_show_titles(show_id, title, source);

CREATE INDEX IF NOT EXISTS idx_tv_show_titles_show_id ON tv_show_titles(show_id);

CREATE TABLE IF NOT EXISTS tv_episodes (
  id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  show_id                 BIGINT      NOT NULL REFERENCES tv_shows(id) ON DELETE CASCADE,
  title                   TEXT        NOT NULL,
  season_number           INT,
  episode_number          INT,
  summary                 TEXT,
  duration_ms             INT,
  originally_available_at DATE,
  fingerprint             TEXT        NOT NULL UNIQUE,
  created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at              TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_tv_episodes_show_id ON tv_episodes(show_id);
CREATE INDEX IF NOT EXISTS idx_tv_episodes_show_season_episode
ON tv_episodes(show_id, season_number, episode_number);

CREATE TABLE IF NOT EXISTS tv_episode_watches (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  episode_id BIGINT      NOT NULL REFERENCES tv_episodes(id) ON DELETE CASCADE,
  source     TEXT        NOT NULL CHECK (source IN ('PLEX', 'MANUAL')),
  watched_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_tv_episode_watches_watched_at ON tv_episode_watches(watched_at DESC);
CREATE INDEX IF NOT EXISTS idx_tv_episode_watches_episode_id ON tv_episode_watches(episode_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_tv_episode_watches_source_episode_watched_at
ON tv_episode_watches(source, episode_id, watched_at);

ALTER TABLE external_identifiers
DROP CONSTRAINT IF EXISTS external_identifiers_entity_type_check,
DROP CONSTRAINT IF EXISTS external_identifiers_provider_check;

ALTER TABLE external_identifiers
ADD CONSTRAINT external_identifiers_entity_type_check
CHECK (entity_type IN ('ARTIST','ALBUM','TRACK','BOOK_EDITION','MOVIE','SHOW','EPISODE')),
ADD CONSTRAINT external_identifiers_provider_check
CHECK (provider IN ('PLEX','SPOTIFY','MUSICBRAINZ','ISBN_10','ISBN_13','TMDB','IMDB','TVDB'));

CREATE INDEX IF NOT EXISTS idx_ext_ids_show
ON external_identifiers(entity_type, entity_id)
WHERE entity_type='SHOW';

CREATE INDEX IF NOT EXISTS idx_ext_ids_episode
ON external_identifiers(entity_type, entity_id)
WHERE entity_type='EPISODE';

CREATE INDEX IF NOT EXISTS idx_ext_ids_entity_provider_external
ON external_identifiers(entity_type, provider, external_id);
