ALTER TABLE tv_shows
ADD COLUMN IF NOT EXISTS cover_url TEXT;

CREATE TABLE IF NOT EXISTS tv_show_images (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  show_id    BIGINT      NOT NULL REFERENCES tv_shows(id) ON DELETE CASCADE,
  url        TEXT        NOT NULL,
  is_primary BOOLEAN     NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_tv_show_images_show_url
ON tv_show_images(show_id, url);

CREATE UNIQUE INDEX IF NOT EXISTS uq_tv_show_images_primary_per_show
ON tv_show_images(show_id)
WHERE is_primary = TRUE;

CREATE INDEX IF NOT EXISTS idx_tv_show_images_show_id ON tv_show_images(show_id);
