CREATE TABLE IF NOT EXISTS movie_collections (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tmdb_id      TEXT        NOT NULL UNIQUE,
  name         TEXT        NOT NULL,
  poster_url   TEXT,
  backdrop_url TEXT,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ
);

ALTER TABLE movies
ADD COLUMN IF NOT EXISTS collection_id BIGINT REFERENCES movie_collections(id) ON DELETE SET NULL;

ALTER TABLE movies
ADD COLUMN IF NOT EXISTS collection_checked_at TIMESTAMPTZ;

CREATE INDEX IF NOT EXISTS idx_movies_collection_id ON movies(collection_id);
CREATE INDEX IF NOT EXISTS idx_movies_collection_checked_at ON movies(collection_checked_at);
