CREATE TABLE IF NOT EXISTS movie_terms (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name            TEXT        NOT NULL,
  normalized_name TEXT        NOT NULL,
  slug            TEXT        NOT NULL,
  kind            TEXT        NOT NULL,
  source          TEXT        NOT NULL,
  hidden          BOOLEAN     NOT NULL DEFAULT FALSE,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_movie_terms_kind_normalized_name
ON movie_terms(kind, normalized_name);

CREATE INDEX IF NOT EXISTS idx_movie_terms_kind_hidden
ON movie_terms(kind, hidden);

CREATE TABLE IF NOT EXISTS movie_term_assignments (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  movie_id    BIGINT      NOT NULL REFERENCES movies(id) ON DELETE CASCADE,
  term_id     BIGINT      NOT NULL REFERENCES movie_terms(id) ON DELETE CASCADE,
  source      TEXT        NOT NULL,
  hidden      BOOLEAN     NOT NULL DEFAULT FALSE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_movie_term_assignments_movie_term
ON movie_term_assignments(movie_id, term_id);

CREATE INDEX IF NOT EXISTS idx_movie_term_assignments_movie_hidden
ON movie_term_assignments(movie_id, hidden);

CREATE INDEX IF NOT EXISTS idx_movie_term_assignments_term_hidden
ON movie_term_assignments(term_id, hidden);
