CREATE TABLE show_credits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    show_id BIGINT NOT NULL REFERENCES tv_shows(id) ON DELETE CASCADE,
    person_id BIGINT NOT NULL REFERENCES people(id) ON DELETE CASCADE,
    credit_type TEXT NOT NULL CHECK (credit_type IN ('CAST', 'CREW')),
    department TEXT,
    job TEXT,
    character_name TEXT,
    billing_order INT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_show_credits_show_id ON show_credits(show_id);
CREATE INDEX idx_show_credits_person_id ON show_credits(person_id);

CREATE UNIQUE INDEX uq_show_credits_show_person_role
    ON show_credits (
        show_id,
        person_id,
        credit_type,
        COALESCE(job, ''),
        COALESCE(character_name, '')
    );
