CREATE TABLE IF NOT EXISTS games (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title          TEXT        NOT NULL,
  original_title TEXT        NOT NULL,
  year           INT,
  description    TEXT,
  cover_url      TEXT,
  slug           TEXT,
  fingerprint    TEXT        NOT NULL UNIQUE,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_games_slug ON games(slug);

CREATE INDEX IF NOT EXISTS idx_games_year ON games(year);

CREATE TABLE IF NOT EXISTS game_images (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game_id    BIGINT      NOT NULL REFERENCES games(id) ON DELETE CASCADE,
  url        TEXT        NOT NULL,
  kind       TEXT        NOT NULL DEFAULT 'GRID',
  is_primary BOOLEAN     NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_game_images_game_url
ON game_images(game_id, url);

CREATE INDEX IF NOT EXISTS idx_game_images_game_id ON game_images(game_id);

CREATE TABLE IF NOT EXISTS game_sessions (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game_id    BIGINT      NOT NULL REFERENCES games(id) ON DELETE CASCADE,
  status     TEXT        NOT NULL CHECK (status IN ('PLAYING','BACKLOG','COMPLETED','ABANDONED')),
  started_at TIMESTAMPTZ NOT NULL,
  ended_at   TIMESTAMPTZ,
  notes      TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_game_sessions_game_activity
ON game_sessions(game_id, started_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS idx_game_sessions_started_at
ON game_sessions(started_at DESC);

ALTER TABLE external_identifiers
DROP CONSTRAINT IF EXISTS external_identifiers_entity_type_check,
DROP CONSTRAINT IF EXISTS external_identifiers_provider_check;

ALTER TABLE external_identifiers
ADD CONSTRAINT external_identifiers_entity_type_check
CHECK (entity_type IN ('ARTIST','ALBUM','TRACK','BOOK','BOOK_EDITION','MOVIE','SHOW','EPISODE','GAME')),
ADD CONSTRAINT external_identifiers_provider_check
CHECK (provider IN ('PLEX','SPOTIFY','MUSICBRAINZ','ISBN_10','ISBN_13','TMDB','IMDB','TVDB','IGDB','STEAMGRIDDB'));

CREATE INDEX IF NOT EXISTS idx_ext_ids_game
ON external_identifiers(entity_type, entity_id)
WHERE entity_type='GAME';
