CREATE TABLE IF NOT EXISTS artists (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         TEXT        NOT NULL,
  fingerprint  TEXT        NOT NULL UNIQUE,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS albums (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  artist_id    BIGINT      NOT NULL REFERENCES artists(id) ON DELETE RESTRICT,
  title        TEXT        NOT NULL,
  year         INT,
  cover_url    TEXT,
  fingerprint  TEXT        NOT NULL UNIQUE,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ,
  CONSTRAINT uq_albums_artist_title_year UNIQUE (artist_id, title, year)
);

CREATE TABLE IF NOT EXISTS tracks (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  album_id      BIGINT      NOT NULL REFERENCES albums(id) ON DELETE CASCADE,
  title         TEXT        NOT NULL,
  track_number  INT,
  disc_number   INT,
  duration_ms   INT,
  fingerprint   TEXT        NOT NULL UNIQUE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_tracks_album_disc_track
ON tracks(album_id, disc_number, track_number)
WHERE disc_number IS NOT NULL AND track_number IS NOT NULL;

CREATE TABLE IF NOT EXISTS external_identifiers (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_type  TEXT NOT NULL CHECK (entity_type IN ('ARTIST','ALBUM','TRACK')),
  entity_id    BIGINT           NOT NULL,   -- FK dinâmica, ver abaixo
  provider     TEXT NOT NULL CHECK (provider IN ('PLEX','SPOTIFY','MUSICBRAINZ')),
  external_id  TEXT             NOT NULL,
  created_at   TIMESTAMPTZ      NOT NULL DEFAULT NOW(),
  UNIQUE (provider, external_id)
);

CREATE INDEX IF NOT EXISTS idx_ext_ids_artist  ON external_identifiers(entity_type, entity_id) WHERE entity_type='ARTIST';
CREATE INDEX IF NOT EXISTS idx_ext_ids_album   ON external_identifiers(entity_type, entity_id) WHERE entity_type='ALBUM';
CREATE INDEX IF NOT EXISTS idx_ext_ids_track   ON external_identifiers(entity_type, entity_id) WHERE entity_type='TRACK';

CREATE TABLE IF NOT EXISTS track_playbacks (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  track_id        BIGINT           NOT NULL REFERENCES tracks(id) ON DELETE CASCADE,
  source          TEXT    NOT NULL CHECK (source IN ('PLEX','SPOTIFY')),
  source_event_id BIGINT,
  played_at       TIMESTAMPTZ      NOT NULL,
  created_at      TIMESTAMPTZ      NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_playbacks_played_at           ON track_playbacks(played_at DESC);
CREATE INDEX IF NOT EXISTS idx_playbacks_track_played_at     ON track_playbacks(track_id, played_at DESC);
CREATE INDEX IF NOT EXISTS idx_playbacks_source_event        ON track_playbacks(source, source_event_id);