CREATE TABLE IF NOT EXISTS artists (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         TEXT        NOT NULL,
  fingerprint  TEXT        NOT NULL UNIQUE,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS albums (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  artist_id    BIGINT      NOT NULL REFERENCES artists(id) ON DELETE RESTRICT,
  title        TEXT        NOT NULL,
  title_key    TEXT        NOT NULL,
  year         INT,
  cover_url    TEXT,
  fingerprint  TEXT        NOT NULL UNIQUE,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ,
  CONSTRAINT uq_albums_artist_titlekey_year UNIQUE (artist_id, title_key, year)
);

CREATE INDEX IF NOT EXISTS idx_albums_artist_title_key
    ON albums(artist_id, title_key);

CREATE INDEX IF NOT EXISTS idx_albums_artist_year
    ON albums(artist_id, year);

CREATE TABLE IF NOT EXISTS tracks (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  artist_id    BIGINT      NOT NULL REFERENCES artists(id) ON DELETE RESTRICT,
  title        TEXT        NOT NULL,
  duration_ms  INT,
  fingerprint  TEXT        NOT NULL UNIQUE,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_tracks_artist_id ON tracks(artist_id);

CREATE TABLE IF NOT EXISTS album_tracks (
  album_id     BIGINT NOT NULL REFERENCES albums(id) ON DELETE CASCADE,
  track_id     BIGINT NOT NULL REFERENCES tracks(id) ON DELETE CASCADE,
  disc_number  INT,
  track_number INT,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (album_id, track_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_album_tracks_position
ON album_tracks(album_id, disc_number, track_number)
WHERE disc_number IS NOT NULL AND track_number IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_album_tracks_album ON album_tracks(album_id);
CREATE INDEX IF NOT EXISTS idx_album_tracks_track ON album_tracks(track_id);

CREATE TABLE IF NOT EXISTS external_identifiers (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_type  TEXT NOT NULL CHECK (entity_type IN ('ARTIST','ALBUM','TRACK')),
  entity_id    BIGINT           NOT NULL,   -- dynamic FK
  provider     TEXT NOT NULL CHECK (provider IN ('PLEX','SPOTIFY','MUSICBRAINZ')),
  external_id  TEXT             NOT NULL,
  created_at   TIMESTAMPTZ      NOT NULL DEFAULT NOW(),
  UNIQUE (provider, external_id)
);

CREATE INDEX IF NOT EXISTS idx_ext_ids_artist  ON external_identifiers(entity_type, entity_id) WHERE entity_type='ARTIST';
CREATE INDEX IF NOT EXISTS idx_ext_ids_album   ON external_identifiers(entity_type, entity_id) WHERE entity_type='ALBUM';
CREATE INDEX IF NOT EXISTS idx_ext_ids_track   ON external_identifiers(entity_type, entity_id) WHERE entity_type='TRACK';

CREATE TABLE IF NOT EXISTS track_playbacks (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  track_id        BIGINT           NOT NULL REFERENCES tracks(id) ON DELETE CASCADE,
  album_id        BIGINT           NOT NULL REFERENCES albums(id) ON DELETE RESTRICT,
  source          TEXT    NOT NULL CHECK (source IN ('PLEX','SPOTIFY')),
  source_event_id BIGINT,
  played_at       TIMESTAMPTZ      NOT NULL,
  created_at      TIMESTAMPTZ      NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_playbacks_played_at           ON track_playbacks(played_at DESC);
CREATE INDEX IF NOT EXISTS idx_playbacks_track_played_at     ON track_playbacks(track_id, played_at DESC);
CREATE INDEX IF NOT EXISTS idx_playbacks_album_played_at     ON track_playbacks(album_id, played_at DESC);
CREATE INDEX IF NOT EXISTS idx_playbacks_source_event        ON track_playbacks(source, source_event_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_playbacks_source_track_album_time
ON track_playbacks(source, track_id, album_id, played_at);

CREATE TABLE IF NOT EXISTS genres (
  id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name  TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS album_genres (
  album_id  BIGINT NOT NULL REFERENCES albums(id) ON DELETE CASCADE,
  genre_id  BIGINT NOT NULL REFERENCES genres(id) ON DELETE RESTRICT,
  PRIMARY KEY (album_id, genre_id)
);

CREATE INDEX IF NOT EXISTS idx_album_genres_album ON album_genres(album_id);
CREATE INDEX IF NOT EXISTS idx_album_genres_genre ON album_genres(genre_id);

CREATE TABLE IF NOT EXISTS album_genre_sources (
  album_id   BIGINT NOT NULL REFERENCES albums(id) ON DELETE CASCADE,
  genre_id   BIGINT NOT NULL REFERENCES genres(id) ON DELETE RESTRICT,
  source     TEXT   NOT NULL CHECK (source IN ('PLEX','MUSICBRAINZ','LASTFM')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (album_id, genre_id, source)
);

CREATE INDEX IF NOT EXISTS idx_album_genre_sources_album ON album_genre_sources(album_id);
CREATE INDEX IF NOT EXISTS idx_album_genre_sources_source ON album_genre_sources(source);

CREATE TABLE IF NOT EXISTS album_genre_sync_state (
  album_id      BIGINT NOT NULL REFERENCES albums(id) ON DELETE CASCADE,
  source        TEXT   NOT NULL CHECK (source IN ('MUSICBRAINZ','LASTFM')),
  status        TEXT   NOT NULL CHECK (status IN ('NEVER','DONE','FAILED')) DEFAULT 'NEVER',
  last_sync_at  TIMESTAMPTZ,
  last_note     TEXT,
  force_next    BOOLEAN NOT NULL DEFAULT FALSE,
  PRIMARY KEY (album_id, source)
);

CREATE INDEX IF NOT EXISTS idx_album_genre_sync_state_source_status
  ON album_genre_sync_state(source, status);

CREATE INDEX IF NOT EXISTS idx_album_genre_sync_state_force_next
  ON album_genre_sync_state(force_next)
  WHERE force_next = TRUE;

CREATE TABLE IF NOT EXISTS spotify_sync_state (
  id BIGSERIAL PRIMARY KEY,
  cursor_after_ms BIGINT NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
