-- === Tipos (ENUMs) ===========================================================
DO $$ BEGIN
  CREATE TYPE provider_enum        AS ENUM ('PLEX','SPOTIFY','MUSICBRAINZ');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
  CREATE TYPE entity_type_enum     AS ENUM ('ARTIST','ALBUM','TRACK');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
  CREATE TYPE playback_source_enum AS ENUM ('PLEX','SPOTIFY');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
  CREATE TYPE event_status_enum    AS ENUM ('RECEIVED','PROCESSED','FAILED');
EXCEPTION WHEN duplicate_object THEN null; END $$;


-- === Core canônico ===========================================================

-- ARTISTS: um artista canônico
CREATE TABLE IF NOT EXISTS artists (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         TEXT        NOT NULL,
  fingerprint  TEXT        NOT NULL UNIQUE,  -- ex: sha256(name-normalizado)
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ
);

-- ALBUMS: um álbum canônico (1 artista principal)
CREATE TABLE IF NOT EXISTS albums (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  artist_id    BIGINT      NOT NULL REFERENCES artists(id) ON DELETE RESTRICT,
  title        TEXT        NOT NULL,
  year         INT,
  cover_url    TEXT,
  fingerprint  TEXT        NOT NULL UNIQUE,  -- ex: sha256(title|artist|year normalizados)
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ,
  -- Um mesmo artista não deve ter dois álbuns com mesmo título e ano
  CONSTRAINT uq_albums_artist_title_year UNIQUE (artist_id, title, year)
);

-- TRACKS: faixa canônica pertencente a um álbum
CREATE TABLE IF NOT EXISTS tracks (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  album_id      BIGINT      NOT NULL REFERENCES albums(id) ON DELETE CASCADE,
  title         TEXT        NOT NULL,
  track_number  INT,
  disc_number   INT,
  duration_ms   INT,                      -- opcional, ajuda a deduplicar
  fingerprint   TEXT        NOT NULL UNIQUE,  -- ex: sha256(title|album|artist|year|disc|track|duration)
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ
);

-- REGRA: evitar duplicidade óbvia de faixa por posição no disco
-- Permite múltiplos NULLs; quando há posição, exige unicidade.
CREATE UNIQUE INDEX IF NOT EXISTS uq_tracks_album_disc_track
ON tracks(album_id, disc_number, track_number)
WHERE disc_number IS NOT NULL AND track_number IS NOT NULL;

-- EXTERNAL_IDENTIFIERS: mapeia IDs externos (Plex, Spotify, MBID) para entidades canônicas
CREATE TABLE IF NOT EXISTS external_identifiers (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_type  entity_type_enum NOT NULL,
  entity_id    BIGINT           NOT NULL,   -- FK dinâmica, ver abaixo
  provider     provider_enum    NOT NULL,
  external_id  TEXT             NOT NULL,
  created_at   TIMESTAMPTZ      NOT NULL DEFAULT NOW(),
  UNIQUE (provider, external_id)
);

-- FK lógica por constraint de integridade de aplicativo:
-- garanta via app que (entity_type, entity_id) aponta para a tabela correta.
-- Índices por entidade para joins rápidos:
CREATE INDEX IF NOT EXISTS idx_ext_ids_artist  ON external_identifiers(entity_type, entity_id) WHERE entity_type='ARTIST';
CREATE INDEX IF NOT EXISTS idx_ext_ids_album   ON external_identifiers(entity_type, entity_id) WHERE entity_type='ALBUM';
CREATE INDEX IF NOT EXISTS idx_ext_ids_track   ON external_identifiers(entity_type, entity_id) WHERE entity_type='TRACK';


-- === Plays ===================================================================

-- TRACK_PLAYBACKS: cada play observado
CREATE TABLE IF NOT EXISTS track_playbacks (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  track_id        BIGINT           NOT NULL REFERENCES tracks(id) ON DELETE CASCADE,
  source          playback_source_enum NOT NULL,
  source_event_id BIGINT,                      -- referência ao event_sources.id quando houver
  played_at       TIMESTAMPTZ      NOT NULL,  -- momento do play (do provider)
  created_at      TIMESTAMPTZ      NOT NULL DEFAULT NOW()
);

-- Índices de análise por período e por faixa
CREATE INDEX IF NOT EXISTS idx_playbacks_played_at           ON track_playbacks(played_at DESC);
CREATE INDEX IF NOT EXISTS idx_playbacks_track_played_at     ON track_playbacks(track_id, played_at DESC);
CREATE INDEX IF NOT EXISTS idx_playbacks_source_event        ON track_playbacks(source, source_event_id);


-- === Ingest (webhooks / importadores) =======================================

-- EVENT_SOURCES: eventos brutos recebidos (Plex webhook, Spotify, etc.)
CREATE TABLE IF NOT EXISTS event_sources (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider       provider_enum     NOT NULL,
  payload        JSONB             NOT NULL,       -- era TEXT; agora JSONB
  fingerprint    TEXT              NOT NULL UNIQUE, -- para dedupe idempotente
  status         event_status_enum NOT NULL DEFAULT 'RECEIVED',
  error_message  TEXT,
  created_at     TIMESTAMPTZ       NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ,
  processed_at   TIMESTAMPTZ
);