ALTER TABLE albums
ADD COLUMN musicbrainz_release_group_id TEXT;

CREATE TABLE album_spotify_ids (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  album_id   BIGINT      NOT NULL REFERENCES albums(id) ON DELETE CASCADE,
  spotify_id TEXT        NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (album_id, spotify_id)
);

CREATE INDEX idx_album_spotify_ids_album_id ON album_spotify_ids(album_id);

CREATE TABLE album_musicbrainz_release_ids (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  album_id   BIGINT      NOT NULL REFERENCES albums(id) ON DELETE CASCADE,
  release_id TEXT        NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (album_id, release_id)
);

CREATE INDEX idx_album_musicbrainz_release_ids_album_id
ON album_musicbrainz_release_ids(album_id);

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM external_identifiers ei
    WHERE ei.entity_type = 'ALBUM'
      AND (
        ei.provider NOT IN ('SPOTIFY', 'MUSICBRAINZ')
        OR (ei.provider = 'SPOTIFY' AND ei.external_entity_type IS NOT NULL)
        OR (
          ei.provider = 'MUSICBRAINZ'
          AND ei.external_entity_type IS NOT NULL
          AND ei.external_entity_type NOT IN ('RELEASE_GROUP', 'RELEASE')
        )
        OR BTRIM(ei.external_id) = ''
        OR (ei.provider = 'SPOTIFY' AND ei.external_id !~ '^[A-Za-z0-9]{22}$')
        OR (
          ei.provider = 'MUSICBRAINZ'
          AND ei.external_id !~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
        )
      )
  ) THEN
    RAISE EXCEPTION 'Invalid ALBUM external identifier found';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM external_identifiers ei
    LEFT JOIN albums a ON a.id = ei.entity_id
    WHERE ei.entity_type = 'ALBUM'
      AND a.id IS NULL
  ) THEN
    RAISE EXCEPTION 'Orphan ALBUM external identifier found';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM external_identifiers ei
    WHERE ei.entity_type = 'ALBUM'
      AND ei.provider = 'MUSICBRAINZ'
      AND ei.external_entity_type = 'RELEASE_GROUP'
    GROUP BY ei.entity_id
    HAVING COUNT(*) > 1
  ) THEN
    RAISE EXCEPTION 'Multiple MusicBrainz release groups for the same album';
  END IF;
END $$;

INSERT INTO album_spotify_ids (album_id, spotify_id, created_at)
SELECT entity_id, external_id, created_at
FROM external_identifiers
WHERE entity_type = 'ALBUM'
  AND provider = 'SPOTIFY';

INSERT INTO album_musicbrainz_release_ids (album_id, release_id, created_at)
SELECT entity_id, external_id, created_at
FROM external_identifiers
WHERE entity_type = 'ALBUM'
  AND provider = 'MUSICBRAINZ'
  AND (external_entity_type = 'RELEASE' OR external_entity_type IS NULL);

UPDATE albums a
SET musicbrainz_release_group_id = ei.external_id
FROM external_identifiers ei
WHERE ei.entity_type = 'ALBUM'
  AND ei.entity_id = a.id
  AND ei.provider = 'MUSICBRAINZ'
  AND ei.external_entity_type = 'RELEASE_GROUP';

DO $$
BEGIN
  IF (SELECT COUNT(*) FROM album_spotify_ids) <>
     (SELECT COUNT(*) FROM external_identifiers WHERE entity_type = 'ALBUM' AND provider = 'SPOTIFY') THEN
    RAISE EXCEPTION 'ALBUM Spotify identifier copy validation failed';
  END IF;

  IF (SELECT COUNT(*) FROM album_musicbrainz_release_ids) <>
     (SELECT COUNT(*) FROM external_identifiers WHERE entity_type = 'ALBUM' AND provider = 'MUSICBRAINZ' AND (external_entity_type = 'RELEASE' OR external_entity_type IS NULL)) THEN
    RAISE EXCEPTION 'ALBUM MusicBrainz release copy validation failed';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM external_identifiers ei
    JOIN albums a ON a.id = ei.entity_id
    WHERE ei.entity_type = 'ALBUM'
      AND ei.provider = 'MUSICBRAINZ'
      AND ei.external_entity_type = 'RELEASE_GROUP'
      AND a.musicbrainz_release_group_id IS DISTINCT FROM ei.external_id
  ) THEN
    RAISE EXCEPTION 'ALBUM MusicBrainz release group copy validation failed';
  END IF;
END $$;

ALTER TABLE albums
ADD CONSTRAINT uq_albums_musicbrainz_release_group_id UNIQUE (musicbrainz_release_group_id);

DELETE FROM external_identifiers WHERE entity_type = 'ALBUM';

DROP INDEX IF EXISTS idx_ext_ids_album;

ALTER TABLE external_identifiers
DROP CONSTRAINT IF EXISTS external_identifiers_entity_type_check;

ALTER TABLE external_identifiers
ADD CONSTRAINT external_identifiers_entity_type_check
CHECK (entity_type IN ('TRACK'));
