CREATE TABLE IF NOT EXISTS authors (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         TEXT        NOT NULL,
  fingerprint  TEXT        NOT NULL UNIQUE,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS books (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title              TEXT        NOT NULL,
  release_date       DATE,
  description        TEXT,
  cover_url          TEXT,
  rating             NUMERIC,
  review_raw         TEXT,
  reviewed_at        TIMESTAMPTZ,
  fingerprint        TEXT        NOT NULL UNIQUE,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at         TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS book_editions (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  book_id      BIGINT      NOT NULL REFERENCES books(id) ON DELETE CASCADE,
  title        TEXT,
  isbn_10      TEXT,
  isbn_13      TEXT,
  pages        INT,
  language     TEXT,
  publisher    TEXT,
  format       TEXT,
  cover_url    TEXT,
  fingerprint  TEXT        NOT NULL UNIQUE,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_book_editions_book_id ON book_editions(book_id);
CREATE INDEX IF NOT EXISTS idx_book_editions_isbn13 ON book_editions(isbn_13);
CREATE INDEX IF NOT EXISTS idx_book_editions_isbn10 ON book_editions(isbn_10);

CREATE TABLE IF NOT EXISTS book_reads (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  book_id         BIGINT      NOT NULL REFERENCES books(id) ON DELETE CASCADE,
  edition_id      BIGINT          REFERENCES book_editions(id) ON DELETE RESTRICT,
  source          TEXT        NOT NULL CHECK (source IN ('HARDCOVER')),
  source_event_id BIGINT      NOT NULL,
  status          TEXT        NOT NULL CHECK (status IN ('READ','CURRENTLY_READING','WANT_TO_READ','DID_NOT_FINISH','PAUSED','UNKNOWN')),
  started_at      TIMESTAMPTZ,
  finished_at     TIMESTAMPTZ,
  progress_pct    NUMERIC,
  progress_pages  INT,
  updated_at      TIMESTAMPTZ,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (source, source_event_id)
);

CREATE INDEX IF NOT EXISTS idx_book_reads_finished_at ON book_reads(finished_at DESC);
CREATE INDEX IF NOT EXISTS idx_book_reads_started_at ON book_reads(started_at DESC);
CREATE INDEX IF NOT EXISTS idx_book_reads_book_id ON book_reads(book_id);
CREATE INDEX IF NOT EXISTS idx_book_reads_status ON book_reads(status);
CREATE INDEX IF NOT EXISTS idx_book_reads_updated_at ON book_reads(updated_at DESC);

CREATE TABLE IF NOT EXISTS book_authors (
  book_id    BIGINT NOT NULL REFERENCES books(id) ON DELETE CASCADE,
  author_id  BIGINT NOT NULL REFERENCES authors(id) ON DELETE RESTRICT,
  role       TEXT   NOT NULL DEFAULT 'AUTHOR',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (book_id, author_id, role)
);

CREATE INDEX IF NOT EXISTS idx_book_authors_book_id ON book_authors(book_id);
CREATE INDEX IF NOT EXISTS idx_book_authors_author_id ON book_authors(author_id);

ALTER TABLE external_identifiers
DROP CONSTRAINT IF EXISTS external_identifiers_entity_type_check,
  DROP CONSTRAINT IF EXISTS external_identifiers_provider_check;

ALTER TABLE external_identifiers
    ADD CONSTRAINT external_identifiers_entity_type_check
        CHECK (entity_type IN ('ARTIST','ALBUM','TRACK','BOOK_EDITION')),
  ADD CONSTRAINT external_identifiers_provider_check
    CHECK (provider IN ('PLEX','SPOTIFY','MUSICBRAINZ','ISBN_10','ISBN_13'));
