CREATE TABLE IF NOT EXISTS genres (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS album_genres (
    album_id  BIGINT NOT NULL REFERENCES albums(id) ON DELETE CASCADE,
    genre_id  BIGINT NOT NULL REFERENCES genres(id) ON DELETE RESTRICT,
    PRIMARY KEY (album_id, genre_id)
);

CREATE INDEX IF NOT EXISTS idx_album_genres_album
    ON album_genres(album_id);

CREATE INDEX IF NOT EXISTS idx_album_genres_genre
    ON album_genres(genre_id);

CREATE INDEX IF NOT EXISTS idx_tracks_album_id
    ON tracks(album_id);

