CREATE TABLE track_spotify_ids (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  track_id   BIGINT      NOT NULL REFERENCES tracks(id) ON DELETE CASCADE,
  spotify_id TEXT        NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (track_id, spotify_id)
);

CREATE INDEX idx_track_spotify_ids_track_id ON track_spotify_ids(track_id);

CREATE TABLE track_musicbrainz_recording_ids (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  track_id     BIGINT      NOT NULL REFERENCES tracks(id) ON DELETE CASCADE,
  recording_id TEXT        NOT NULL UNIQUE,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (track_id, recording_id)
);

CREATE INDEX idx_track_musicbrainz_recording_ids_track_id
ON track_musicbrainz_recording_ids(track_id);

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM external_identifiers ei
    WHERE ei.entity_type <> 'TRACK'
  ) THEN
    RAISE EXCEPTION 'Unexpected non-TRACK external identifier found';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM external_identifiers ei
    WHERE ei.entity_type = 'TRACK'
      AND (
        ei.provider NOT IN ('SPOTIFY', 'MUSICBRAINZ')
        OR (ei.provider = 'SPOTIFY' AND ei.external_entity_type IS NOT NULL)
        OR (
          ei.provider = 'MUSICBRAINZ'
          AND ei.external_entity_type IS NOT NULL
          AND ei.external_entity_type <> 'RECORDING'
        )
        OR BTRIM(ei.external_id) = ''
        OR (ei.provider = 'SPOTIFY' AND ei.external_id !~ '^[A-Za-z0-9]{22}$')
        OR (
          ei.provider = 'MUSICBRAINZ'
          AND ei.external_id !~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
        )
      )
  ) THEN
    RAISE EXCEPTION 'Invalid TRACK external identifier found';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM external_identifiers ei
    LEFT JOIN tracks t ON t.id = ei.entity_id
    WHERE ei.entity_type = 'TRACK'
      AND t.id IS NULL
  ) THEN
    RAISE EXCEPTION 'Orphan TRACK external identifier found';
  END IF;
END $$;

INSERT INTO track_spotify_ids (track_id, spotify_id, created_at)
SELECT entity_id, external_id, created_at
FROM external_identifiers
WHERE entity_type = 'TRACK'
  AND provider = 'SPOTIFY';

INSERT INTO track_musicbrainz_recording_ids (track_id, recording_id, created_at)
SELECT entity_id, external_id, created_at
FROM external_identifiers
WHERE entity_type = 'TRACK'
  AND provider = 'MUSICBRAINZ'
  AND (external_entity_type = 'RECORDING' OR external_entity_type IS NULL);

DO $$
BEGIN
  IF (SELECT COUNT(*) FROM track_spotify_ids) <>
     (SELECT COUNT(*) FROM external_identifiers WHERE entity_type = 'TRACK' AND provider = 'SPOTIFY') THEN
    RAISE EXCEPTION 'TRACK Spotify identifier copy validation failed';
  END IF;

  IF (SELECT COUNT(*) FROM track_musicbrainz_recording_ids) <>
     (SELECT COUNT(*) FROM external_identifiers WHERE entity_type = 'TRACK' AND provider = 'MUSICBRAINZ' AND (external_entity_type = 'RECORDING' OR external_entity_type IS NULL)) THEN
    RAISE EXCEPTION 'TRACK MusicBrainz recording copy validation failed';
  END IF;
END $$;

DROP TABLE external_identifiers;
