CREATE TABLE album_title_aliases (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  album_id   BIGINT      NOT NULL REFERENCES albums(id) ON DELETE CASCADE,
  artist_id  BIGINT      NOT NULL REFERENCES artists(id) ON DELETE CASCADE,
  title      TEXT        NOT NULL,
  title_key  TEXT        NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT album_title_aliases_artist_title_key_unique UNIQUE (artist_id, title_key)
);

CREATE INDEX idx_album_title_aliases_album_id ON album_title_aliases(album_id);

CREATE TABLE album_musicbrainz_release_group_aliases (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  album_id         BIGINT      NOT NULL REFERENCES albums(id) ON DELETE CASCADE,
  release_group_id TEXT        NOT NULL UNIQUE,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT album_mb_release_group_alias_album_unique UNIQUE (album_id, release_group_id)
);

CREATE INDEX idx_album_mb_release_group_aliases_album_id
ON album_musicbrainz_release_group_aliases(album_id);

