DROP TABLE IF EXISTS book_reads;

CREATE TABLE IF NOT EXISTS book_reads (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  book_id             BIGINT      NOT NULL REFERENCES books(id) ON DELETE CASCADE,
  edition_id          BIGINT          REFERENCES book_editions(id) ON DELETE RESTRICT,
  source              TEXT        NOT NULL CHECK (source IN ('HARDCOVER')),
  source_session_id   BIGINT      NOT NULL,
  source_container_id BIGINT,
  status              TEXT        NOT NULL CHECK (status IN ('READ','CURRENTLY_READING','WANT_TO_READ','DID_NOT_FINISH','PAUSED','UNKNOWN')),
  started_at          TIMESTAMPTZ,
  finished_at         TIMESTAMPTZ,
  progress_pct        NUMERIC,
  progress_pages      INT,
  updated_at          TIMESTAMPTZ,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (source, source_session_id)
);

CREATE INDEX IF NOT EXISTS idx_book_reads_finished_at ON book_reads(finished_at DESC);
CREATE INDEX IF NOT EXISTS idx_book_reads_started_at ON book_reads(started_at DESC);
CREATE INDEX IF NOT EXISTS idx_book_reads_book_id ON book_reads(book_id);
CREATE INDEX IF NOT EXISTS idx_book_reads_status ON book_reads(status);
CREATE INDEX IF NOT EXISTS idx_book_reads_updated_at ON book_reads(updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_book_reads_source_container_id ON book_reads(source_container_id);
