ALTER TABLE movies
    ADD COLUMN favorite BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN abandoned BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE tv_shows
    ADD COLUMN favorite BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN abandoned BOOLEAN NOT NULL DEFAULT FALSE;
