CREATE TABLE IF NOT EXISTS movies (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  original_title TEXT        NOT NULL,
  year           INT,
  description    TEXT,
  fingerprint    TEXT        NOT NULL UNIQUE,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_movies_year ON movies(year);

CREATE TABLE IF NOT EXISTS movie_titles (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  movie_id   BIGINT      NOT NULL REFERENCES movies(id) ON DELETE CASCADE,
  title      TEXT        NOT NULL,
  locale     TEXT,
  source     TEXT        NOT NULL CHECK (source IN ('PLEX')),
  is_primary BOOLEAN     NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_movie_titles_movie_title_source
ON movie_titles(movie_id, title, source);

CREATE INDEX IF NOT EXISTS idx_movie_titles_movie_id ON movie_titles(movie_id);

CREATE TABLE IF NOT EXISTS movie_watches (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  movie_id   BIGINT      NOT NULL REFERENCES movies(id) ON DELETE CASCADE,
  source     TEXT        NOT NULL CHECK (source IN ('PLEX')),
  watched_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_movie_watches_watched_at ON movie_watches(watched_at DESC);
CREATE INDEX IF NOT EXISTS idx_movie_watches_movie_id ON movie_watches(movie_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_movie_watches_source_movie_watched_at
ON movie_watches(source, movie_id, watched_at);

ALTER TABLE external_identifiers
DROP CONSTRAINT IF EXISTS external_identifiers_entity_type_check,
DROP CONSTRAINT IF EXISTS external_identifiers_provider_check;

ALTER TABLE external_identifiers
ADD CONSTRAINT external_identifiers_entity_type_check
CHECK (entity_type IN ('ARTIST','ALBUM','TRACK','BOOK_EDITION','MOVIE')),
ADD CONSTRAINT external_identifiers_provider_check
CHECK (provider IN ('PLEX','SPOTIFY','MUSICBRAINZ','ISBN_10','ISBN_13','TMDB','IMDB'));

CREATE INDEX IF NOT EXISTS idx_ext_ids_movie
ON external_identifiers(entity_type, entity_id)
WHERE entity_type='MOVIE';
