ALTER TABLE movies
ADD COLUMN IF NOT EXISTS cover_url TEXT;

CREATE TABLE IF NOT EXISTS movie_images (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  movie_id   BIGINT      NOT NULL REFERENCES movies(id) ON DELETE CASCADE,
  url        TEXT        NOT NULL,
  is_primary BOOLEAN     NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_movie_images_movie_url
ON movie_images(movie_id, url);

CREATE UNIQUE INDEX IF NOT EXISTS uq_movie_images_primary_per_movie
ON movie_images(movie_id)
WHERE is_primary = TRUE;

CREATE INDEX IF NOT EXISTS idx_movie_images_movie_id ON movie_images(movie_id);
