### Playback Summary API

### Top by month
GET {{host}}/playbacks/top?period=month
Content-Type: application/json

### Top by week
GET {{host}}/playbacks/top?period=week
Content-Type: application/json

### Top by day
GET {{host}}/playbacks/top?period=day
Content-Type: application/json


### Top by year
GET {{host}}/playbacks/top/2025?limit=100
Content-Type: application/json

### Recent playbacks
GET {{host}}/playbacks/recent
Content-Type: application/json