version: '3.8'
services:
  api:
    build:
      context: ../
      dockerfile: server/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev

#  site:
#    build:
#      context: ../
#      dockerfile: ../web/Dockerfile
#    ports:
#      - "3000:3000"
#    depends_on:
#      - api
