@eventId = 4905

###
POST {{host}}/event-sources/reprocess
Content-Type: application/json

{
  "all": true,
  "pageSize": 50
}

### Reprocess pending events
POST {{host}}/event-sources/reprocess
Content-Type: application/json

{
  "all": true,
  "status": ["PENDING"],
  "pageSize": 50
}

### Reprocess by id
POST {{host}}/event-sources/{{eventId}}/reprocess
Content-Type: application/json
